### ISSUE TITLE
[BUG] fraglimit doesn't works properly on teamplay modes

### ISSUE THREAD

**Issue by BillyKido** [QW-Group/ktx#176]
fragslimit cmd working only on player (works in duel) but with 2on2 or 4on4 it's doesn't work (is tied to the player and not to the team). For example with fragsup to 50, duel match ending when player got 50th, in 2on2 match when team got 50 nothing happened, only when one player in team got it, match was over. didn't find any other cmd's for teamplay fraglimit.

 - Operation System: Windows 10
 - Processor Architecture: x86_64
 - MVDSV Version: 0.33
 - KTX Version: 1.39

**Comment by tcsabina** [comment]
PR #264 takes care of this
