### ISSUE TITLE
XonXonX issues with frag/kill feed

### ISSUE THREAD

**Issue by mushis** [QW-Group/ktx#187]
related to #165

problems in 2on2on2 (at least):
* rpickup doesn't work. it will rpickup and set two teams only, instead of three.
* tracker shows green messages (friendly kills enemy) for enemy's killing enemys.

**Comment by mushis** [comment]
Here is a demo:
[2on2_1_vs_red_vs_a[dm2]211018-2330.zip](https://github.com/deurk/ktx/files/7374605/2on2_1_vs_red_vs_a.dm2.211018-2330.zip)

Enemy killing enemy should be displayed in red, imo. green is teamfrags. imo.
Another thing its "wrong" and should be adjusted is the demo name prefix: its '2on2' instead of '2on2on2' or 'XonX'.

**Comment by tcsabina** [comment]
mushi.
let this issue handle the tracker problem.
for the rpickup, there is https://github.com/QW-Group/ktx/issues/190
and for the demo name, there will be another issue (not sure if under KTX or mvdsv)

**Comment by tcsabina** [comment]
Tracker is an ezquake hud element, so it has nothing to do with KTX. Opened https://github.com/QW-Group/ezquake-source/issues/715.
Closing this

**Comment by tcsabina** [comment]
@mushis,
The fix for this is in ezquake in a recent snapshot build (thanks to krizej). Could you test it, and comment on the ticket there (https://github.com/QW-Group/ezquake-source/issues/715)? Thanks!
