### ISSUE TITLE
Strange status text visible while spectating certain players

### ISSUE THREAD

**Issue by tcsabina** [QW-Group/ktx#189]
Report from Milton:
![unknown](https://user-images.githubusercontent.com/17887592/142594875-9c0f183c-b814-4077-bb9e-25771ede7226.png)

> hud_editor doesn't see it
hud_score_bar_show 0 doesn't help
they disappear when I open the console
(and come back when I close console)
and only some players have it
now only gor
if I switch pov to any other player, the extra stuff disappears

**Comment by tcsabina** [comment]
Some tips from Discord:

pattah: 
> yea, it's like hud_score_bar for ktx
used it back in ktpro days

hangtime:
> I think it's like setinfo ks or something like that
Although I think that would only change normal spec not qtv
Ktpro used to display that if you set the ks (kteams scores) flag iirc

**Comment by tcsabina** [comment]
This status text looks very similar to the XonXonX status report, so I need to investigate.

**Comment by qqshka** [comment]
it is +scores command and it is not a bug, lol.
