### ISSUE TITLE
[BUG] download_map_url http://maps.quakeworld.eu/ points to NXDOMAIN

### ISSUE THREAD

**Issue by nvtkaszpir** [QW-Group/ktx#191]
**Describe the bug**
download_map_url              "http://maps.quakeworld.eu/" points to NXDOMAIN

https://github.com/deurk/ktx/blob/master/resources/example-configs/ktx/mvdsv.cfg#L90

**Comment by tcsabina** [comment]
PR #222 is solving this

**Comment by nvtkaszpir** [comment]
thx!
