### ISSUE TITLE
Rpickup retry doesn't work

### ISSUE THREAD

**Issue by HangTimeQW** [QW-Group/ktx#211]
If rpickup selects the same teams as current, server states it will retry up to 3 times.  But it doesn't generate different teams it just keeps dame teams.  Doesn't look like it is triggering a retry.

**Comment by tcsabina** [comment]
Hmm, I will look into this.
But of course, it is a bit tricky to test, as we need to generate the same team layout for the recursion to trigger :D.


Regards,
Toma

**Comment by HangTimeQW** [comment]
I guess it could be tested in 2on2 as this would drastically reduce the number of potential team permutations?

**Comment by mushis** [comment]
on a side note, why does it even state that it will be retried? the expected result is different teams than current, doesn't matter how many times it retries.
my opinion.

**Comment by tcsabina** [comment]
@HangTimeQW ,

I've found a small bug in this: if an (elected)admin issued the 'rpickup' the recursive calls were not triggered.
I've fixed this now.

Toma

**Comment by tcsabina** [comment]
PR #225 fixes this
