### ISSUE TITLE
Create documentation for the recently added Clan Arena changes

### ISSUE THREAD

**Issue by tcsabina** [QW-Group/ktx#218]
Hey @dusty-qw ,

I am calling out for some help regarding the recent changes you have made. The PR is merged, so the only thing left is some sort of documentation.

The bare minimum will be to have an overview about the features/bugfixes you have added/solved, in a plain simple list view. In a format that can be added to the Release Notes.
Please take a look on the last Release Notes: https://github.com/QW-Group/ktx/releases/tag/v1.40
To have an idea what I mean.

But of course we should not stop with the Release Notes when we talk about documentation. That is a must, and I really want at least that contain the recent changes. But we can go further if we want.
I am not sure how well should a mod like CA be documented. But I leave it up to you to think about it ;).
Maybe some ingame help to explain certain commands?
Maybe some wiki-kind of page that explains the commands/mod?

Regards,
Toma

**Comment by tcsabina** [comment]
Hello @dusty-qw ,

Have you seen this? :)

Regards,
Toma

**Comment by dusty-qw** [comment]
Now I see it :) thanks for the heads up!

**Comment by dusty-qw** [comment]
Hi Toma,

How would you like the overview? I can just put it here for now. Also I'm going to make another PR at some point with some additions and fixes, and that will include some kind of ingame help. There's very few commands or anything at this point so I'm not sure if a dedicated wiki is necessary:

Clan Arena / Wipeout
- Revamped clan arena mode (/carena) to hopefully retire the old CACE mod
- New Wipeout mode (/wipeout) allows players to respawn after increasing intervals
- First person spectator support for dead players
- End-of-round and end-of-game stats
- Proper support for team overlay
- Original CA sounds for countdown, "DRO!", etc.
- Various bug fixes and other improvements

**Comment by tcsabina** [comment]
Hi dusty!

This is Perfect, dude! :) Excellence!
