### ISSUE TITLE
[BUG] Remove non-free code from tarball

### ISSUE THREAD

**Issue by leegarrett** [QW-Group/ktx#256]
**Describe the bug**
`tools/q3lcc` seems to be a fork of https://github.com/ec-/q3lcc. It's `CPYRIGHT` file however contains a custom license that is incompatible with GPLv2+ (it restricts commercial use). For that reason I'd remove it.

It also seems like `tools/q3asm` is just another fork of https://github.com/ec-/q3asm, if it's not used for anything I'd just remove it, too.

**Comment by leegarrett** [comment]
I have created [PR#257](https://github.com/QW-Group/ktx/pull/257) for this.

**Comment by tcsabina** [comment]
Hello Lee!

KTX is not a commercial product, so I think we are quite safe here ;).

**Comment by leegarrett** [comment]
I think you're misunderstanding this. q3lcc restricts commercial use, which makes the complete ktx release tarballs not distributable under the GPLv2 license.

**Comment by ciscon** [comment]
we're not releasing compiled versions of that binary nor at any point is it being linked in/called by our binary, the only redistribution that's being done is of source code which is fine, a repo can have code under different licenses.

**Comment by tcsabina** [comment]
PR #257 tackles this.
