### ISSUE TITLE
[BUG] Sum of Armour times greater than match length

### ISSUE THREAD

**Issue by HangTimeQW** [QW-Group/ktx#258]
**Describe the bug**
I have observed in end game stats that the sum of armour times for a given player can be longer than the length of the match, which should be impossible.  For example a player had 11:24 RA and 11:21 YA during a 20min game.  This doesn't make sense because you can only have 1 armour at time.

**To Reproduce**
Grab loads of armours stacking red on yellow on green I guess.

**Expected behavior**
Armour times total less than match duration.  It should not be counting armour time concurrently, there should be max 1 armour being counted at any point in time.

**Screenshots**
See Raket's stats in screenshot
![e1m2_355](https://user-images.githubusercontent.com/71505905/194083974-1cb767f7-8f2d-4e31-a282-b5e690a4226b.png)

**Environment(please complete the following information):**
KTX 1.41

**Comment by mushis** [comment]
the Mega times also look wrong.
personally, I find this stat useless.

**Comment by tcsabina** [comment]
PR #264 takes care of this
