### ISSUE TITLE
"streak" is wrong on midair mode

### ISSUE THREAD

**Issue by mushis** [QW-Group/ktx#260]
It seems that the endstat "Streak" is calculated incorrectly on midair game mode.

![image](https://user-images.githubusercontent.com/3011167/194709035-12fe3f0c-3c28-4080-9bd7-d743047cba28.png)

ktx 1.42 dev

**Comment by tcsabina** [comment]
Hey mushi!
From the screenshot it is not obvious that it is wrong ;).
So you died between the 26 kills, you say?

I took a quick peek on the code. The midair stat is using the same variable as the normal game. So if this is wrong in midair, it will be wrong in a normal game mode as well.

Anyhow, I will do some testing with a bot...

**Comment by tcsabina** [comment]
Mushi,
I did a quick match with a bot, and with 2 clients of my own. It looks okay to me.

**Comment by mushis** [comment]
so, I killed the enemy 26 times in total.
he killed me 4.
how can I have a 26 streak?

**Comment by tcsabina** [comment]
Hi mushi,

I have finally found the bug. It was in the original endgame stats, not introduced with the new one. Fixed anyhow..

Thanks for reporting!

**Comment by tcsabina** [comment]
PR #264 takes care of this
