### ISSUE TITLE
[Q] How to define map pool?

### ISSUE THREAD

**Issue by lockheed** [QW-Group/ktx#347]
It's been a while since I was into this so I am a bit rusty. Where in KTX/MVDSV do you define the specific maps pool for specific game mode 1on1, 2on2, etc?
Same question for FFA-mode map rotation.

**Comment by ciscon** [comment]
it can be done elsewhere but by default it's done in the matchless config as that's the only time it's used:
https://github.com/QW-Group/ktx/blob/master/resources/example-configs/ktx/configs/usermodes/matchless/default.cfg
there is no map pool for any other modes, all maps are voted on.

**Comment by lockheed** [comment]
Yes, but you can't vote on a map that is not on the list. I want to know how to add a map to the list.

**Comment by ciscon** [comment]
the list is generated from the bsp files in the maps directory, just add more maps and they'll show up.  if you want them to show up without restarting the server you need to vote for a map (any map) and then reconnect to get the updated aliases.

**Comment by lockheed** [comment]
Interesting. Back in the day, you had to enable the maps you wanted. Not sure if just having them around makes more sense.
