### ISSUE TITLE
CA: Spectate (Teammates?) After Death

### ISSUE THREAD

**Issue by thistlew** [QW-Group/ktx#40]
Sorry if this is already a feature and we just missed it, but my friends and I were playing CA KTX last night and found ourselves unable to spectate through the eyes of our teammates after we died. Instead, we just had to float around and look for the action. Personally, I think it'd be cool if you had two different options (toggle-able via command in game, maybe admin only):

1) Spectate through anyone's (including enemies) eyes
2) Spectate through only your teammates' eyes

Any official games would obviously use the second option, but it'd be nice to have access to the first option if you're just playing with friends and goofing around.

**Comment by tcsabina** [comment]
@dusty-qw ,
I am tagging you on this as well (and on all CA-tagged issues). I hope you don't mind.

Could you make a decision:
- to close, as 'wont' fix'
- to close, as 'solved'
- leave open, and tackle it

**Comment by dusty-qw** [comment]
solved
