### ISSUE TITLE
MOTD: dynamic motd

### ISSUE THREAD

**Issue by mushis** [QW-Group/ktx#45]
Would be cool that the motd printed everytime a player connects could be flexible.

for example, if there's a file called motd on /ktx, print that. otherwise, print whatever is set on k_motd*

server admins could add news to that file, such as:

> maps added: q1q3tourney
> matchless ctf on port 28505

**Comment by blaps** [comment]
This is good. Up+

**Comment by tcsabina** [comment]
Hi @mushis,

I had a short chat about this feature request within the team. And ciscon pointed out that actually you can already achieve what you are up to, without any changes:
nowdays the nquakesv installer creates unique configuration files for each server port you are running. These 'port_2850N.cfg' files contain port specific stuff, including the motd of that particular port. So if you want to update your port's motd without restart, just modify those 'set k_motdX' lines in the port config, and just reload the config with 'exec port_2850N.cfg' in the server console. You can use rcon as well to execute the 'exec command'.

So I am going to close this issue as 'won't do'.

**Comment by mushis** [comment]
fairynuff :)
still i was wondering if there is a way an admin could do that more easily. From web maybe?
