### ISSUE TITLE
CA: Various issues

### ISSUE THREAD

**Issue by meag** [QW-Group/ktx#50]
Clan arena isn't used in KTX, so should just be modified until other servers running clan-arena-specific mods can be deleted.

Bugs reported:

- [ ] the voice at matchstart is gone
  - believe this is an issue with the copyright of the original sounds?  maybe make a user-specific setinfo to enable, and have them spawned using `/play` instead of `sound()`?
- [ ] the spectating (after death) does not work
  - should be locked to the player's current team only (use race mode's chasecam?)
- [ ] the mod setting reverts to 2on2 on mapchange, i.e. you have to set /carena again

**Comment by tcsabina** [comment]
@dusty-qw ,

Yet another one:

Could you make a decision:
- to close, as 'wont' fix'
- to close, as 'solved'
- leave open, and tackle it

**Comment by dusty-qw** [comment]
solved

**Comment by tcsabina** [comment]
Available from v1.41
