### ISSUE TITLE
REQ: Race route for bravado

### ISSUE THREAD

**Issue by VVD** [QW-Group/ktx#58]
[bravado.route](https://github.com/deurk/ktx/files/3193497/bravado.route.txt)
3 routes.

**Comment by VVD** [comment]
[bravado.route.txt](https://github.com/deurk/ktx/files/4737625/bravado.route.txt)
Added 4th race - fixed race 2.

**Comment by tcsabina** [comment]
Hi @VVD,
I've just discovered this! Thanks for your contribution.
Sorry that it took 3 years...

**Comment by tcsabina** [comment]
PR #310
