### ISSUE TITLE
CA: Clan Arena mode doesn't match classic Clan Arena mod

### ISSUE THREAD

**Issue by meag** [QW-Group/ktx#68]
Thanks to [D_P]BLooD_DoG for the list

We played a few rounds and compared to KTX CA and came up with these differences:

1. Unable to spec teammates when dead (only floating)
2. Chat while dead should not go to players still alive, only to other dead players/specs
3. Missing 3 second delay after spawn, before countdown starts
4. Missing 3 second delay at end of round, after last person dies
5. Oldschool CA sounds aren't playing (countdown/winner/draw ("DRO"))
6. Stats need work, see screenshots. The KTX stats have all the data, but the tabular/summary format is more useful in regular CA because you don't have time to scroll up between rounds to see everyone's individual stats when you only have a few seconds
7. Player disappears instantly when killed, looks weird
8. Missing "Sudden Death" feature (after 'x' minutes, 20 second timer appears after which all players still alive get teleported to pent area to finish the round, so that the rounds don't last forever). Only applies to dm3?
9. Support 3 teams (yellow)
10. You make a damage sound when teammate hits you even though you take no damage (taking no damage is correct, sound isn't)
11. Should not take damage when falling
12. Default RL ammo should be 60, LG should be 100, GL (counted separately from RL) should be 20
13. Teamoverlay shows teammates as full stack when they're dead
14. Scoreboard doesn't show you who is dead and who is alive (can't tell how many enemies and teammates are left in a round)

**Comment by meag** [comment]
#1 we could maybe use the race chasecam?
#2 should be doable, the mod has decided chat for a long time
#3 add 3 seconds to countdown timer, only show after the 3 seconds are up?
#4 should be okay
#5 isn't this a copyright issue?  remember seeing something about this before
#6 meh
#7 ok
#8 any idea what x is?  I think this does only apply to DM3, do we have the source code for the old mod so we know what the coordinates are?
#9 ok
#10 ok
#11 ok - but should you still make a noise?
#12 what happens when they've fired 20 grenades?  Doesn't this break weapon scripts?
#13 & #14 fixed by setting team to 'dead' once dead?

**Comment by tcsabina** [comment]
Hi @dusty-qw,

Is your recent PR solving all of these issues?

Regards,
Toma

**Comment by dusty-qw** [comment]
Yes. I used this list as a starting point. The only things not addressed are support for 3 teams and the sudden death feature.

**Comment by tcsabina** [comment]
@dusty-qw ,
The 3 teams might be easy now, that there are the 2on2on2 and 3on3on3 modes available. Are you willing to investigate?

**Comment by tcsabina** [comment]
@dusty-qw ,
I am closing this, and creating a new issue for the remaining 2 items (3 teams and Sudden Death).
